schema_version: 1

context:
  name: getopt-win32
  version: 0.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/libimobiledevice-win32/getopt/archive/${{ version }}.tar.gz
  sha256: 7e9653ecd58ce4149959bf6a905f4ab2f7889856fe1218afbf84284074f9e549
  patches:
    # https://github.com/libimobiledevice-win32/getopt/pull/3
    # https://github.com/libimobiledevice-win32/getopt/pull/1
    - better_compatibility_with_vs2022.patch
    - 0001-inject-cmake-project.patch

build:
  number: 3
  skip: not win
  script:
    - cmake %CMAKE_ARGS% -S . -B build
    - cmake -LH build
    - cmake --build build --config=Release
    - cmake --install build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
  run_exports:
    - ${{ pin_subpackage('getopt-win32', upper_bound='x.x.x') }}

tests:
  - package_contents:
      files:
        - Library/lib/cmake/unofficial-getopt-win32/unofficial-getopt-win32*.cmake
      include:
        - getopt.h
      lib:
        - getopt.lib
      bin:
        - getopt.dll

about:
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A port of getopt for Visual C++
  homepage: https://vcpkg.info/port/getopt-win32
  repository: https://github.com/libimobiledevice-win32/getopt

extra:
  recipe-maintainers:
    - nehaljwani
